export const EstadosECidades = [
    { estado: 'Acre', cidades: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira', 'Tarauacá'] },
    { estado: 'Alagoas', cidades: ['Maceió', 'Arapiraca', 'Rio Largo', 'Palmeira dos Índios'] },
    { estado: 'Amapá', cidades: ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque'] },
    { estado: 'Amazonas', cidades: ['Manaus', 'Itacoatiara', 'Parintins', 'Manacapuru'] },
    { estado: 'Bahia', cidades: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari'] },
    { estado: 'Ceará', cidades: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú'] },
    { estado: 'Distrito Federal', cidades: ['Brasília'] },
    { estado: 'Espírito Santo', cidades: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica'] },
    { estado: 'Goiás', cidades: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Rio Verde'] },
    { estado: 'Maranhão', cidades: ['São Luís', 'Imperatriz', 'São José de Ribamar', 'Caxias'] },
    { estado: 'Mato Grosso', cidades: ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop'] },
    { estado: 'Mato Grosso do Sul', cidades: ['Campo Grande', 'Dourados', 'Três Lagoas', 'Corumbá'] },
    { estado: 'Minas Gerais', cidades: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora'] },
    { estado: 'Pará', cidades: ['Belém', 'Ananindeua', 'Santarém', 'Marabá'] },
    { estado: 'Paraíba', cidades: ['João Pessoa', 'Campina Grande', 'Santa Rita', 'Patos'] },
    { estado: 'Paraná', cidades: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Campo Mourão'] },
    { estado: 'Pernambuco', cidades: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru'] },
    { estado: 'Piauí', cidades: ['Teresina', 'Parnaíba', 'Picos', 'Floriano'] },
    { estado: 'Rio de Janeiro', cidades: ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu'] },
    { estado: 'Rio Grande do Norte', cidades: ['Natal', 'Mossoró', 'Parnamirim', 'São Gonçalo do Amarante'] },
    { estado: 'Rio Grande do Sul', cidades: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas'] },
    { estado: 'Rondônia', cidades: ['Porto Velho', 'Ji-Paraná', 'Cacoal', 'Vilhena'] },
    { estado: 'Roraima', cidades: ['Boa Vista', 'Rorainópolis', 'Cantá', 'Alto Alegre'] },
    { estado: 'Santa Catarina', cidades: ['Florianópolis', 'Joinville', 'Blumenau', 'São José'] },
    { estado: 'São Paulo', cidades: ['São Paulo', 'Guarulhos', 'Campinas', 'São Bernardo do Campo'] },
    { estado: 'Sergipe', cidades: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana'] },
    { estado: 'Tocantins', cidades: ['Palmas', 'Araguaína', 'Gurupi', 'Paraíso do Tocantins'] }
    //
  // Adicione mais estados e suas cidades conforme necessário
];